### ISSUE TITLE
Invalid URL in lda2vec.readthedocs.io

### ISSUE THREAD

**Issue by JiaxiangBU** [cemoody/lda2vec#101]
Here is the location

```
Resources
See this Jupyter Notebook for an example of an end-to-end demonstration.
https://nbviewer.jupyter.org/github/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda.ipynb
```
The origin file found by 'Edit on GitHub' is https://github.com/cemoody/lda2vec/blob/master/docs/index.rst

**Comment by lordtt13** [comment]
Please check this link:
https://nbviewer.jupyter.org/github/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec.ipynb

**Comment by JiaxiangBU** [comment]
Thanks, it works for me.
