### ISSUE TITLE
Jupyter notebook does not exist

### ISSUE THREAD

**Issue by stared** [cemoody/lda2vec#13]
The notebook linked in http://nbviewer.jupyter.org/github/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda.ipynb (line 31 of README.rst) does not exist.

**Comment by evandrix** [comment]
*bump*

**Comment by dipanjanS** [comment]
Facing the same issue

**Comment by tingletech** [comment]
FWIW https://github.com/cemoody/lda2vec/blob/e1005872c5e439a9ca90af1390076e855e9eda50/examples/twenty_newsgroups/lda.ipynb

**Comment by tingletech** [comment]
Also http://nbviewer.jupyter.org/github/cemoody/lda2vec/blob/e1005872c5e439a9ca90af1390076e855e9eda50/examples/twenty_newsgroups/lda.ipynb

**Comment by cemoody** [comment]
Yep, will include. I reorganized the code to be a bit cleaner, but this then outdated the ipynb file. When the new models finish running, I'll update the ipynb. Thanks for popping this up, didn't notice it's loss at first glance :)

**Comment by cemoody** [comment]
Notebook is here:
https://github.com/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec.ipynb
Viewable from here:
http://nbviewer.jupyter.org/github/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec.ipynb
