### ISSUE TITLE
It seems that the main LDA2Vec.py file has been deleted, as well as the notebook

### ISSUE THREAD

**Issue by cjmcmurtrie** [cemoody/lda2vec#21]
It seems that the main module, lda2vec.py, as well as the iPython nb have been deleted.

Are you keeping this repository open source for us to try out, or not? If not please say so because I've already spent significant time trying to get it running. Thanks!

**Comment by nipunsadvilkar** [comment]
@cjmcmurtrie : ipynb notebook is available .
 Visit this link: http://nbviewer.jupyter.org/github/cemoody/lda2vec/blob/e1005872c5e439a9ca90af1390076e855e9eda50/examples/twenty_newsgroups/lda.ipynb#topic=9&lambda=0.27&term=

**Comment by cemoody** [comment]
Hi @cjmcmurtrie, I've simplified the model and broken the monolithic `lda2vec.py` into a set of smaller, individually-tested modules. You'll find the new model file here https://github.com/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec_model.py

And the notebook is here:
https://github.com/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec.ipynb
Viewable from here:
http://nbviewer.jupyter.org/github/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec.ipynb
