### ISSUE TITLE
Getting JSON SPACY Issue

### ISSUE THREAD

**Issue by samcarlos** [cemoody/lda2vec#24]
I get the error below. I tried to install spacy with force all but that didn't fix the problem. 

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-1-13be9aab2321> in <module>()
     22 max_length = 10000   # Limit of 10k words per document
     23 tokens, vocab = preprocess.tokenize(texts, max_length, tag=False,
---> 24                                     parse=False, entity=False)
     25 corpus = Corpus()
     26 # Make a ranked list of rare vs frequent words

//anaconda/lib/python2.7/site-packages/lda2vec-0.1-py2.7.egg/lda2vec/preprocess.pyc in tokenize(texts, max_length, skip, attr, **kwargs)
     63     if nlp is None:
     64         data_dir = os.environ.get('SPACY_DATA', LOCAL_DATA_DIR)
---> 65         nlp = English(data_dir=data_dir)
     66     data = np.zeros((len(texts), max_length), dtype='int32')
     67     data[:] = skip

//anaconda/lib/python2.7/site-packages/spacy/language.pyc in __init__(self, data_dir, vocab, tokenizer, tagger, parser, entity, matcher, serializer, load_vectors, package)
    229 
    230         if vocab in (None, True):
--> 231             vocab = self.default_vocab(package)
    232         self.vocab = vocab
    233         if tokenizer in (None, True):

//anaconda/lib/python2.7/site-packages/spacy/language.pyc in default_vocab(cls, package, get_lex_attr)
    163                 get_lex_attr = cls.default_lex_attrs()
    164         if hasattr(package, 'dir_path'):
--> 165             return Vocab.from_package(package, get_lex_attr=get_lex_attr)
    166         else:
    167             return Vocab.load(package, get_lex_attr)

//anaconda/lib/python2.7/site-packages/spacy/vocab.pyx in spacy.vocab.Vocab.from_package (spacy/vocab.cpp:3592)()
     63                               lemmatizer=lemmatizer, serializer_freqs=serializer_freqs)
     64 
---> 65         with package.open(('vocab', 'strings.json')) as file_:
     66             self.strings.load(file_)
     67         self.load_lexemes(package.file_path('vocab', 'lexemes.bin'))

//anaconda/lib/python2.7/contextlib.pyc in __enter__(self)
     15     def __enter__(self):
     16         try:
---> 17             return self.gen.next()
     18         except StopIteration:
     19             raise RuntimeError("generator didn't yield")

//anaconda/lib/python2.7/site-packages/sputnik/package_stub.pyc in open(self, path_parts, mode, encoding, default)
     65         else:
     66             if isinstance(default, type) and issubclass(default, Exception):
---> 67                 raise default(self.file_path(*path_parts))
     68             elif isinstance(default, Exception):
     69                 raise default

IOError: //anaconda/lib/python2.7/site-packages/spacy/en/data/vocab/strings.json

**Comment by realdoug** [comment]
@samcarlos I got the same error.  I was able to resolve the error by running this:

`python -m spacy.en.download --force`  

If you _still_ get the error then you need to figure out what directory spacy is downloading it's data to and add set the SPACY_DATA env variable in your shell.

**Comment by cemoody** [comment]
Yeah, the preprocessing code has been updated so should be fixed. Definitely a fix for me (largely because I keep changing virtual envs) is to do `python -m spacy.en.download --force`
