### ISSUE TITLE
Requires cuda

### ISSUE THREAD

**Issue by PavlosMelissinos** [cemoody/lda2vec#26]
Are there any plans to run exclusively on a cpu?

**Comment by cemoody** [comment]
You should be able to modify the lda2vec_run.py pretty quickly. Removing the `model.to_gpu()` is likely the only thing you need to do.

**Comment by PavlosMelissinos** [comment]
Indeed, removing every reference to gpu or cuda seems to work.

Thanks for making this publicly available.
