### ISSUE TITLE
model.py and visualize.py files missing

### ISSUE THREAD

**Issue by nanader** [cemoody/lda2vec#29]
Hi,

I wanted to replicate an end-to-end process with the example of hacker news from the page:
https://github.com/cemoody/lda2vec/tree/master/examples/hacker_news

I have found the file preprocess.py, but where are the files model.py and visualize.py? I can't find them anywhere on the github page

**Comment by cemoody** [comment]
OK, updated! There should be files for the Hacker News corpus are here:

https://github.com/cemoody/lda2vec/blob/master/examples/hacker_news/lda2vec/lda2vec.ipynb

https://github.com/cemoody/lda2vec/blob/master/examples/hacker_news/lda2vec/lda2vec_model.py

https://github.com/cemoody/lda2vec/blob/master/examples/hacker_news/lda2vec/word_vectors.ipynb
