### ISSUE TITLE
TypeError trying to visualize npzfile data with pyLDAvis

### ISSUE THREAD

**Issue by mepatterson** [cemoody/lda2vec#3]
new to using pyLDAvis, but I ran the 20 newsgroups example, which generated `topics.pyldavis.npz`
after loading that into `npzfile`, did the following
```python
import pyLDAvis as vis

prepared_data = vis.prepare(npzfile['topic_term_dists'],npzfile['doc_topic_dists'],npzfile['doc_lengths'],npzfile['vocab'],npzfile['term_frequency'])

vis.prepared_data_to_html(prepared_data)
```
but I just get a TypeError
```
TypeError: 5.3336749 is not JSON serializable
```
(same error if I try to use `show()` or `display()` or anything else that expected PreparedData, though if i just `print prepared_data`, it looks the data contains reasonable topics and vocab...)

Am I just doing something wrong or is there a bug?

**Comment by cemoody** [comment]
I issued a pull request with pyLDAvis that should fix this issue. Could you try installing the latest pyLDAvis from their master branch?

**Comment by mepatterson** [comment]
yep, that worked. thanks
