### ISSUE TITLE
The lda2vec package should have a big warning for Windows users

### ISSUE THREAD

**Issue by nanader** [cemoody/lda2vec#32]
Hi,

One probably final comment from me. The lda2vec package should have a **HUGE  warning sign** that trying it on a Windows is a big challenge. Making dependencies work on a windows is really a pain and requires great depths of experience in working on similar problems.

Chainer doesn't really work on Windows systems. I learned to appreciate the magnitude of the problem only later into my work with lda2vec. For the record, I did manage to run the preprocessing and modelling code from the Hacker News example after quite significant modifications of the code but it was a very time consuming feat and with limited success. For example, cuDNN still doesn't work and I need to do any computations on CPU. Adapting this package to a windows system on one's own computer only achievable for well trained IT experts with experience

All the best,
RK

**Comment by cemoody** [comment]
Yeah, agreed. The installation is difficult, especially when GPUs are involved. And oh man, once you hit Windows....

Will update the README!

**Comment by cemoody** [comment]
Updated README to establish expectations that this is research software :)

**Comment by nanader** [comment]
The package has awesome potential I think. Thanks for your good work :)
