### ISSUE TITLE
Strength of the dirichlet prior

### ISSUE THREAD

**Issue by TropComplique** [cemoody/lda2vec#58]
Hi! 
In file
[`examples/twenty_newsgroups/lda2vec/lda2vec_run.py`](https://github.com/cemoody/lda2vec/blob/master/examples/twenty_newsgroups/lda2vec/lda2vec_run.py)
hyperparameter `clambda = 200.0` is never used, I believe.
I think strength of the dirichlet prior is actually `1.0` there.

**Comment by ghost** [comment]
How did you solve this?
It seems to be `-1.0` instead of `1.0` according to here: https://github.com/cemoody/lda2vec/blob/b7f4642b750c6e792c07d177bd57ad36e65bb35c/lda2vec/dirichlet_likelihood.py#L34
