### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by hirenaum97** [cemoody/lda2vec#67]
File "/home/aum/PycharmProjects/learn_p/venv/src/lda2vec/lda2vec/preprocess.py", line 35, in tokenize
    assert dat.min() >= 0, msg
AssertionError: Negative indices reserved for special tokens

what should i do?

**Comment by bountrisv** [comment]
What version of spacy are you using? As is mentioned in the comments before line 35 this is usually spacy's thing - if it fails. Changing spacy version to 1.9.0 made it work for me.

**Comment by hirenaum97** [comment]
thanks, but this error occuring
--> numpy.core._internal.AxisError: axis -1 is out of bounds for array of dimension 0

**Comment by bountrisv** [comment]
This is unrelated to the first issue. Possibly, you have fewer tokens than the 20000 that is the default top parameter. Try lowering that parameter, or adjusting the maximum size of the data array.

**Comment by richzt** [comment]
Python2.7 and python3 can be used interchangeably to pass those error.

**Comment by Aravinviju** [comment]
Which solution worked for this issue???


---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-41-53fd260f090e> in <module>()
      4 texts = [str(clean(d)) for d in texts]
      5 tokens, vocab = preprocess.tokenize(texts, max_length, merge=False,
----> 6                                     n_threads=4)

~/Arav/LDA2VEC_TopicModel/lda2vec-master/lda2vec/preprocess.py in tokenize(texts, max_length, skip, attr, merge, nlp, **kwargs)
     91             dat = dat.astype('int32')
     92             msg = "Negative indices reserved for special tokens"
---> 93             assert (dat.min() >= 0), msg
     94             # Replace email and URL tokens
     95             idx = (dat[:, 1] > 0) | (dat[:, 2] > 0)

AssertionError: Negative indices reserved for special tokens

**Comment by Aravinviju** [comment]
even after Changing spacy version to 1.9.0, gives me the same error!
Can someone help?

**Comment by bountrisv** [comment]
> This is unrelated to the first issue. Possibly, you have fewer tokens than the 20000 that is the default top parameter. Try lowering that parameter, or adjusting the maximum size of the data array.

**Comment by Aravinviju** [comment]
Sorry, I didn't really get the solution. What exactly do you mean by fewer tokens?
Should I increase the 'n_threads' ?

by asking to adjust the maximum size of the data array, are you referring to the 'max_length' parameter?

Sorry, that i couldn't understand the solution. I am new to this and just trying to work around it.

**Comment by bountrisv** [comment]
Are you using the original dataset?

**Comment by Aravinviju** [comment]
Yea, I am using the default 'fetch_20newsgroups' from sklearn.datasets.

**Comment by bountrisv** [comment]
I see. I can not help much more other than to suggest trying some more spacy versions, like 1.8.0. Sorry.

**Comment by Aravinviju** [comment]
Okay, I'll try different versions of spacy.

Can you tell me what you meant by, 'fewer tokens' and 'maximum size of the data array'? could be helpful for me!

**Comment by LizaKoz** [comment]
Hi everyone,

Did anybody solve this issue?
I have spacy==2.0.5 and still getting this problem...

**Comment by abose17** [comment]
Badly seeking the exact solution! Does anyone have right now since then?

**Comment by ranjeetkgupta** [comment]
Changing spacy version to 1.9.0 worked for me !!!
