### ISSUE TITLE
File Missing: 'GoogleNews-vectors-negative300.bin'

### ISSUE THREAD

**Issue by ghost** [cemoody/lda2vec#90]
In `twenty_newsgroups/data`, I can't run `preprocess.py` since a file is missing. It's stuck at the following code block:

    # Fill in the pretrained word vectors
    n_dim = 300
    fn_wordvc = 'GoogleNews-vectors-negative300.bin'
    vectors, s, f = corpus.compact_word_vectors(vocab, filename=fn_wordvc)

**Comment by whcjimmy** [comment]
This is the offical website for that file. 
https://code.google.com/archive/p/word2vec/
You can download the file from "Pre-trained word and phrase vectors" section.
